# Generated by Django 5.2.4 on 2025-07-31 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_marks_of_user_completed_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='marks_of_user',
            options={'ordering': ['-completed_at'], 'verbose_name': 'User Progress', 'verbose_name_plural': 'User Progress'},
        ),
        migrations.AddField(
            model_name='marks_of_user',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='marks_of_user',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='marks_of_user',
            name='completed_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
